name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Prisma generate
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          # Mock environment variables for CI build
          DATABASE_URL: "mongodb://localhost:27017/ci_test"
          NEXTAUTH_SECRET: "ci-test-secret-key-for-github-actions"
          NEXTAUTH_URL: "http://localhost:3000"
          GEMINI_API_KEY: "dummy-key-for-ci"
          NEXT_PUBLIC_SUPABASE_URL: "https://dummy.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "dummy-key"
        run: npm run build


