name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH_HOST
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ SSH_HOST is empty or not set"
            exit 1
          else
            echo "✅ SSH_HOST is set (length: ${#SSH_HOST})"
          fi
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Test SSH_USER
        run: |
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "❌ SSH_USER is empty or not set"
            exit 1
          else
            echo "✅ SSH_USER is set"
          fi
      
      - name: Test SSH_KEY
        run: |
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "❌ SSH_KEY is empty or not set"
            exit 1
          else
            echo "✅ SSH_KEY is set (length: ${#SSH_KEY})"
          fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      
      - name: Test DATABASE_URL
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "❌ DATABASE_URL is empty or not set"
            exit 1
          else
            echo "✅ DATABASE_URL is set"
          fi
      
      - name: Test NEXTAUTH_SECRET
        run: |
          if [ -z "${{ secrets.NEXTAUTH_SECRET }}" ]; then
            echo "❌ NEXTAUTH_SECRET is empty or not set"
            exit 1
          else
            echo "✅ NEXTAUTH_SECRET is set"
          fi
      
      - name: Test NEXTAUTH_URL
        run: |
          if [ -z "${{ secrets.NEXTAUTH_URL }}" ]; then
            echo "❌ NEXTAUTH_URL is empty or not set"
            exit 1
          else
            echo "✅ NEXTAUTH_URL is set"
          fi
      
      - name: All Secrets OK
        run: echo "🎉 All required secrets are configured!"

